"""Train and export the independent audio model in Teachable Machine's browser UI.

Requires Playwright and system Chrome. The ZIPs are generated by
``audio_dataset/scripts/make_gtm_imports.py`` from train-split recordings only.
This script neither signs in nor uploads the held-out validation/test clips.
"""

from __future__ import annotations

import json
import code
import zipfile
from pathlib import Path

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "gtm_model/upload_package/tm_imports/index.json"
EXPORT = ROOT / "gtm_model"


def main() -> None:
    classes = json.loads(INDEX.read_text(encoding="utf-8"))
    ordered = [next(item for item in classes if item["class"] == "Background Noise")]
    ordered += [item for item in classes if item["class"] != "Background Noise"]
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(
            executable_path="/usr/bin/google-chrome", headless=True,
            args=["--no-sandbox", "--disable-dev-shm-usage"],
        )
        page = browser.new_page(viewport={"width": 1440, "height": 900}, accept_downloads=True)
        page.on("console", lambda message: print("browser error:", message.text[:250], flush=True)
                if message.type == "error" else None)
        page.goto("https://teachablemachine.withgoogle.com/train/audio", wait_until="domcontentloaded")
        page.wait_for_timeout(5500)
        page.mouse.click(416, 464)  # Dismiss the introductory tour if present.

        for index, item in enumerate(ordered):
            if index > 1:
                page.get_by_text("Add a class", exact=True).click()
            if index > 0:
                page.locator('svg[aria-label="Edit class name"]').nth(index).click()
                field = page.locator("input#label-input").nth(index)
                field.fill(item["class"])
                field.press("Enter")
            page.locator('input[type=file][accept="application/zip"]').nth(index).set_input_files(
                str(ROOT / item["zip"])
            )
            page.get_by_text("Loading sample...", exact=False).wait_for(
                state="hidden", timeout=120000
            )
            print("Imported", item["class"], item["sample_count"], flush=True)

        page.screenshot(path="/tmp/gtm-ready.png", full_page=True)
        print("buttons before training", [x.strip() for x in page.locator("button").all_text_contents()][-25:], flush=True)
        page.get_by_role("button", name="Train Model").last.evaluate("e => e.click()")
        print("Training started", flush=True)
        page.wait_for_timeout(3000)
        for interval in range(80):
            page.wait_for_timeout(15000)
            labels = [label.strip() for label in page.locator("button").all_text_contents()]
            print("Training interval", interval + 1,
                  [label for label in labels if "Train" in label or "Export" in label], flush=True)
            if "Model Trained" in labels:
                break
        else:
            raise TimeoutError("Teachable Machine did not finish training within 20 minutes")

        page.screenshot(path="/tmp/gtm-trained.png", full_page=True)
        page.get_by_role("button", name="Export Model").click()
        page.wait_for_timeout(2500)
        radios = page.get_by_role("radio", name="Download")
        if radios.count():
            radios.last.check(force=True)
        else:
            page.get_by_text("Download", exact=True).last.click()
        page.wait_for_timeout(1000)
        print("export buttons", [x.strip() for x in page.locator("button").all_text_contents()][-30:], flush=True)
        print("export radios", page.locator('input[type="radio"]').evaluate_all(
            "els => els.map(e => e.outerHTML.slice(0,300))"), flush=True)
        page.screenshot(path="/tmp/gtm-export-dialog.png", full_page=True)
        try:
            with page.expect_download(timeout=120000) as downloaded:
                page.get_by_role("button", name="Download my model").click()
        except Exception as exc:
            print("Export needs manual inspection:", exc, flush=True)
            code.interact(local={"page": page, "browser": browser,
                                 "export_dir": EXPORT, "zipfile": zipfile})
            return
        archive_path = ROOT / "gtm_model/teachable_machine_export.zip"
        downloaded.value.save_as(archive_path)
        print("Exported", archive_path, flush=True)
        with zipfile.ZipFile(archive_path) as archive:
            print("Contents", archive.namelist(), flush=True)
            for entry in archive.infolist():
                name = Path(entry.filename).name
                if name in {"metadata.json", "model.json", "weights.bin"}:
                    (EXPORT / name).write_bytes(archive.read(entry))
        page.screenshot(path="/tmp/gtm-export.png", full_page=True)
        browser.close()


if __name__ == "__main__":
    main()
